#PRACTICAL QUESTIONS

##1  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [6]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array_3x3 = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns (transpose the array)
transposed_array = array_3x3.T

# Print the original and transposed arrays
print("Original Array:")
print(array_3x3)

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[54 77 19]
 [15  8 65]
 [28 15 37]]

Transposed Array:
[[54 15 28]
 [77  8 15]
 [19 65 37]]


##2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [9]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # Array from 0 to 9

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Print the original and reshaped arrays
print("Original 1D Array:")
print(array_1d)

print("\nReshaped into 2x5 Array:")
print(array_2x5)

print("\nReshaped into 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


##3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [12]:
import numpy as np

# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to create a 6x6 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the original and bordered arrays
print("Original 4x4 Array:")
print(array_4x4)

print("\n6x6 Array with Zero Border:")
print(array_with_border)


Original 4x4 Array:
[[0.55606271 0.05729563 0.6543203  0.65902468]
 [0.34706669 0.45959526 0.67448892 0.08529008]
 [0.01985373 0.30327851 0.83806986 0.02729336]
 [0.38420889 0.04389822 0.795268   0.05969929]]

6x6 Array with Zero Border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.55606271 0.05729563 0.6543203  0.65902468 0.        ]
 [0.         0.34706669 0.45959526 0.67448892 0.08529008 0.        ]
 [0.         0.01985373 0.30327851 0.83806986 0.02729336 0.        ]
 [0.         0.38420889 0.04389822 0.795268   0.05969929 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


##4  Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [15]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 65, 5)
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


##5  Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
(uppercase, lowercase, title case, etc.) to each element.

In [18]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply case transformations
upper_case = np.char.upper(string_array)
lower_case = np.char.lower(string_array)
title_case = np.char.title(string_array)

print(upper_case)
print(lower_case)
print(title_case)


['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


##6  Generate a NumPy array of words. Insert a space between each character of every word in the array

In [21]:
import numpy as np

# Generate a NumPy array of words
words_array = np.array(['apple', 'banana', 'cherry'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words_array)

print(spaced_words)


['a p p l e' 'b a n a n a' 'c h e r r y']


##7 Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [24]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

# Print the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


##8  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [27]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the results
print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


##9  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array.

In [30]:
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Print the results
print("Random Integers:\n", random_integers)
print("Prime Numbers:\n", prime_numbers)


Random Integers:
 [434 377 730 359 788 961 176  62 213 506 215 222 747 424 132 788 935 870
 915 262  94 918 926 222  52 529 671 343 192 790 156 340 500 547 531 965
 859 128 601 558 215 722 156 667 883 668 441  39 390 602 243 310 153 714
 224 235 730 853 643 235 245 154  92 929  68 391 532 609 981 905 661 615
 461 162 860 214 359 213 147 676 757 873 311 861 436 965 647 152 276 336
 217  69 392 715 654 771 109 618 688 610]
Prime Numbers:
 [359, 547, 859, 601, 883, 853, 643, 929, 661, 461, 359, 757, 311, 647, 109]


##10  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages.

In [33]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For example, using random temperatures between 15 and 30 degrees Celsius
daily_temperatures = np.random.randint(15, 31, size=30)

# Reshape the array into a 4x7 matrix (4 weeks)
# We can ignore the last two days for the sake of simplicity
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Print the results
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("Weekly Temperatures:\n", weekly_temperatures)
print("Weekly Averages:\n", weekly_averages)


Daily Temperatures for the Month:
 [19 17 17 24 21 25 16 30 15 27 16 26 30 20 26 16 25 30 24 27 26 25 21 19
 17 18 24 29 19 30]
Weekly Temperatures:
 [[19 17 17 24 21 25 16]
 [30 15 27 16 26 30 20]
 [26 16 25 30 24 27 26]
 [25 21 19 17 18 24 29]]
Weekly Averages:
 [19.85714286 23.42857143 24.85714286 21.85714286]
